name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4ec83ced07b15afd81b2295be3afae58cd4de148875864d434f0b3597f618b7"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
