name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b82e97c269b6b7a23a5905bf3ac2510ba39da71516e0f6ad96d21784eac71c8b"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
