name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34e254af107e358d6983bc27ab82e9ddd71e8b4c52c217f5ad77dc1075685d95"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
