name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e52e13b70521dd593c035c9f1cf14647d78e148fae18c5e56d1f7899ddf2a06"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
