name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "990382c34ec60c4bf42632e28acbf2eb6d43fc4e6d7c9cf08ec139af0336be2f"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
