name = "Experience 2"
author = "Soochaehwa"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe5d40a8f852e6fb23af37ceb03c08251010768ab024df8ea4df2938d9bd223b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
