name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f93cb240988d84dfcb78449d82384ee9b2adfbf6848a3421e156bcc2cc2a553a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
