name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "555dae4d8121fae4dd5a9b455cff97e30621f99c47cfddfab9f08d4fab71effe"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
