name = "test"
author = "test"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33298f4946492f66a78eaca1587511ef371cb5c76d39dcf3a8c52deedf99cac8"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
