name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1587b8126fb768e0dabc77b5431efefd4208ed3e8d8aa58bad093cc864900e4d"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
