name = "Experience 2"
author = "Soochaehwa"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44d53fd63c6e4aad3c70f6c0ecc53cf6d2c18dcaa06cf5080054e03c18d073f2"

[versions]
fabric = "0.11.3"
minecraft = "1.17"

[options]
acceptable-game-versions = "1.16.5"
