name = "Experience 2"
author = "Soochaehwa"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "503854f3da156aa2b55d49c5a58fb2b18470cedbbc01a44b0bf23f74c25646e0"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
