name = "Experience 2"
author = "Soochaehwa"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cdddc4124ce4226ab4e62b416102a6a92611f40ed73bf2707167a8a2a199555"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
