name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "939a0531347fd1edbea74a603db29019ec989c2ab705e7ead78f993b3474cc6e"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
