name = "Experience 2"
author = "Soochaehwa"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19d9967c75ce992b89d527e35d8f0d958fbb8afb11e07f779190598fb8f23679"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
