name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba57ad483ab6884ef0ac8c3544a6b775ae1f2ab1d62e110aeb3c2a3310666b96"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
