name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6aeb5fc0ef38fffa2e378436f3530369d5fdf17ec43679bc4a5f8ae78a208cd"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
