name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed7d3fa67befed28413947b4b99e0bf3f05961e9314e38c2460d5bebf6a15ed1"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
