name = "Experience 2"
author = "Soochaehwa"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21aa21bcf546a47ce3f0fb68f8b55d115388ab98a5fa8c91b2df90a73654403b"

[versions]
fabric = "0.11.3"
minecraft = "1.17"

[options]
acceptable-game-versions = "1.16.5"
