name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a72a4e8bfb8d8901869916a2358f9cdf4346b29f6b75769be0c4b147928c80bc"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
