name = "Experience 2"
author = "Soochaehwa"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92db6055fe117b411bf21c7f4b7c5256c994c799e28f1acda4e4efbe20c3337f"

[versions]
fabric = "0.11.3"
minecraft = "1.17"

[options]
acceptable-game-versions = "1.16.5"
