name = "Experience 2"
author = "Soochaehwa"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5725789caafa056a99b747d48cc1f3e93c29c74557ec836f53ae21f996018e"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
