name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46b6184604e8b721b5439f86e8d1a77e637dbdb3f494d13a681af8d6c21544ee"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
