name = "test"
author = "test"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33afc047bf76b61b796f22190ed7adbd243252cc3638efb0bdcaa587580bffc1"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
