name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d2ee5157e32bfd88a1ee96c0c70e0265773d00636abfd38c2f3b1a86c4970aa"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
