name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15bf9d4f3615becc03d10bbb650bc39bff8d1bcc47e62f60226b330d188e6fef"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
