name = "Experience 2"
author = "Soochaehwa"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f497d02f04af2b9e609f5f5b9a3f6270c53dd8cd853183e1a7515c1f912c0b24"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
