name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "257fcecdf075f1b5ef04519c6531dee76a14219f84786c1758dad78cac7d18cf"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
