name = "Experience 2"
author = "Soochaehwa"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eae12cbfc9090e24172718b7662593d76817234c42ca4557335d60e40c3b4859"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
