name = "Experience^2"
author = "SooChaehwa"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9227499c2baa6af6cffd3d1f728a318a93b4bf3eb61d9c277516936feecd2b0a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
