name = "Adaptive Brightness"
filename = "adaptivebrightness-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/305/adaptivebrightness-1.0.jar"
hash-format = "murmur2"
hash = "869992285"

[update]
[update.curseforge]
file-id = 3344305
project-id = 492267
release-channel = "beta"
