name = "Adaptive Brightness"
filename = "adaptivebrightness-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/652/adaptivebrightness-1.0.1.jar"
hash-format = "murmur2"
hash = "1162389239"

[update]
[update.curseforge]
file-id = 3349652
project-id = 492267
release-channel = "beta"
