name = "Architectury API (Fabric)"
filename = "architectury-1.9.136-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/486/architectury-1.9.136-fabric.jar"
hash-format = "murmur2"
hash = "3840137278"

[update]
[update.curseforge]
file-id = 3245486
project-id = 419697
release-channel = "beta"
