name = "Architectury API (Fabric)"
filename = "architectury-1.8.131-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3229/581/architectury-1.8.131-fabric.jar"
hash-format = "murmur2"
hash = "2661741939"

[update]
[update.curseforge]
file-id = 3229581
project-id = 419697
release-channel = "beta"
