name = "Architectury API (Fabric)"
filename = "architectury-1.9.132-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3241/425/architectury-1.9.132-fabric.jar"
hash-format = "murmur2"
hash = "3193389264"

[update]
[update.curseforge]
file-id = 3241425
project-id = 419697
release-channel = "beta"
