name = "Architectury API (Fabric)"
filename = "architectury-1.10.138-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/257/architectury-1.10.138-fabric.jar"
hash-format = "murmur2"
hash = "1595115745"

[update]
[update.curseforge]
file-id = 3248257
project-id = 419697
release-channel = "beta"
