name = "Architectury API (Fabric)"
filename = "architectury-1.17.20-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/632/architectury-1.17.20-fabric.jar"
hash-format = "murmur2"
hash = "4275008659"

[update]
[update.curseforge]
file-id = 3330632
project-id = 419697
release-channel = "beta"
