name = "Architectury API (Fabric)"
filename = "architectury-1.13.153-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3307/824/architectury-1.13.153-fabric.jar"
hash-format = "murmur2"
hash = "16471742"

[update]
[update.curseforge]
file-id = 3307824
project-id = 419697
release-channel = "beta"
