name = "Autofish"
filename = "Autofish-0.9.3-fabric-mc1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3347/260/Autofish-0.9.3-fabric-mc1.17.jar"
hash-format = "murmur2"
hash = "3684467811"

[update]
[update.curseforge]
file-id = 3347260
project-id = 319473
release-channel = "beta"
