name = "Better Biome Blend"
filename = "betterbiomeblend-1.16.4-1.1.4-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3264/892/betterbiomeblend-1.16.4-1.1.4-fabric.jar"
hash-format = "murmur2"
hash = "1255057768"

[update]
[update.curseforge]
file-id = 3264892
project-id = 446253
release-channel = "beta"
