name = "Better Sodium Video Settings Button"
filename = "BetterSodiumVideoSettingsButton-1.0.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/973/BetterSodiumVideoSettingsButton-1.0.2.1.jar"
hash-format = "murmur2"
hash = "2096503287"

[update]
[update.curseforge]
file-id = 3213973
project-id = 437443
release-channel = "beta"
