name = "Better Third Person"
filename = "BetterThirdPerson-Fabric-1.16.4-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/940/BetterThirdPerson-Fabric-1.16.4-1.4.0.jar"
hash-format = "murmur2"
hash = "2338860322"

[update]
[update.curseforge]
file-id = 3222940
project-id = 435044
release-channel = "beta"
