name = "Better Sodium Video Settings Button"
filename = "BetterSodiumVideoSettingsButton-1.0.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/626/BetterSodiumVideoSettingsButton-1.0.3.1.jar"
hash-format = "murmur2"
hash = "639566836"

[update]
[update.curseforge]
file-id = 3245626
project-id = 437443
release-channel = "beta"
