name = "Better Biome Blend"
filename = "betterbiomeblend-1.16.4-1.1.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3228/996/betterbiomeblend-1.16.4-1.1.3-fabric.jar"
hash-format = "murmur2"
hash = "2911825434"

[update]
[update.curseforge]
file-id = 3228996
project-id = 446253
release-channel = "beta"
