name = "Better Third Person"
filename = "BetterThirdPerson-Fabric-1.17-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/646/BetterThirdPerson-Fabric-1.17-1.5.0.jar"
hash-format = "murmur2"
hash = "1971775677"

[update]
[update.curseforge]
file-id = 3343646
project-id = 435044
release-channel = "beta"
