name = "Boosted Brightness"
filename = "boosted-brightness-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/27/boosted-brightness-2.1.0.jar"
hash-format = "murmur2"
hash = "2103427071"

[update]
[update.curseforge]
file-id = 3359027
project-id = 386460
release-channel = "beta"
