name = "Boosted Brightness"
filename = "boosted-brightness-2.0.0+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3353/688/boosted-brightness-2.0.0+1.16.5.jar"
hash-format = "murmur2"
hash = "1173573093"

[update]
[update.curseforge]
file-id = 3353688
project-id = 386460
release-channel = "beta"
