name = "Boosted Brightness"
filename = "boosted-brightness-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3154/915/boosted-brightness-1.2.1.jar"
hash-format = "murmur2"
hash = "1217890454"

[update]
[update.curseforge]
file-id = 3154915
project-id = 386460
release-channel = "beta"
