name = "Canvas Renderer"
filename = "canvas-mc117-1.17-1.0.1641.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3357/916/canvas-mc117-1.17-1.0.1641.jar"
hash-format = "murmur2"
hash = "3146147558"

[update]
[update.curseforge]
file-id = 3357916
project-id = 318440
release-channel = "beta"
