name = "Canvas Renderer"
filename = "canvas-mc117-1.17-1.0.1630.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3350/484/canvas-mc117-1.17-1.0.1630.jar"
hash-format = "murmur2"
hash = "512021819"

[update]
[update.curseforge]
file-id = 3350484
project-id = 318440
release-channel = "beta"
