name = "Canvas Renderer"
filename = "canvas-mc117-1.17-1.0.1604.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/895/canvas-mc117-1.17-1.0.1604.jar"
hash-format = "murmur2"
hash = "1035054104"

[update]
[update.curseforge]
file-id = 3346895
project-id = 318440
release-channel = "beta"
