name = "ChestTracker"
filename = "chesttracker-1.16.5-0.8.11.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ni4SrKmq/versions/0.8.11/chesttracker-1.16.5-0.8.11.jar"
hash-format = "sha512"
hash = "56ed77a4e03a5f3069c7319e1cb815462000fadeed9a75bc507b1def6f058ec48024b0a60ab0aed9c2f0aa7bb13a4b45ca11982ced07dcd3e8f93ed5319de3c0"

[update]
[update.modrinth]
mod-id = "ni4SrKmq"
version = "BpoFsaKs"
