name = "Durability Viewer"
filename = "durabilityviewer-1.17-fabric0.34.9-1.10.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/LTM1f0yY/versions/1.17-fabric0.34.9-1.10.1/durabilityviewer-1.17-fabric0.34.9-1.10.1.jar"
hash-format = "sha512"
hash = "b9bd40938aec277063ecf87deeac5d7f8e27095a1a5fc958e50b34d7a7b4a4eeca45ca24cb80a42fc3ee89acab71572cfdbfa690703f361411410cb4ddd64f03"

[update]
[update.modrinth]
mod-id = "LTM1f0yY"
version = "J80q62Gq"
