name = "Dynamic Music"
filename = "dynmus-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3314/565/dynmus-1.2.0.jar"
hash-format = "murmur2"
hash = "280195167"

[update]
[update.curseforge]
file-id = 3314565
project-id = 430824
release-channel = "beta"
