name = "Dynamic Music"
filename = "dynamic-music-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3212/101/dynamic-music-1.1.0.jar"
hash-format = "murmur2"
hash = "972746913"

[update]
[update.curseforge]
file-id = 3212101
project-id = 430824
release-channel = "beta"
