name = "EasierVillagerTrading"
filename = "easiervillagertrading-1.17-fabric0.34.9-1.5.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ChscgScW/versions/1.17-fabric0.34.9-1.5.4/easiervillagertrading-1.17-fabric0.34.9-1.5.4.jar"
hash-format = "sha512"
hash = "9241f0ff90afcef47245c0971cd6a222abdd615dab2da1d743892fcc4e364e161d2ada008985c160855a594ca280e0ad17967079cf627ab8d28d7e6bf80a0191"

[update]
[update.modrinth]
mod-id = "ChscgScW"
version = "icKLQUE9"
