name = "EntityCulling Fabric/Forge"
filename = "EntityCulling-Fabric-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3233/326/EntityCulling-Fabric-1.0.4.jar"
hash-format = "murmur2"
hash = "2882866089"

[update]
[update.curseforge]
file-id = 3233326
project-id = 448233
release-channel = "beta"
