name = "Fabric API"
filename = "fabric-api-0.35.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/733/fabric-api-0.35.1+1.17.jar"
hash-format = "murmur2"
hash = "4062321292"

[update]
[update.curseforge]
file-id = 3349733
project-id = 306612
release-channel = "beta"
