name = "Fabric API"
filename = "fabric-api-0.35.1+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3352/232/fabric-api-0.35.1+1.16.jar"
hash-format = "murmur2"
hash = "3352834949"

[update]
[update.curseforge]
file-id = 3352232
project-id = 306612
release-channel = "beta"
