name = "FastChest"
filename = "fast-chest-1.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/1/fast-chest-1.2+1.17.jar"
hash-format = "murmur2"
hash = "61993830"

[update]
[update.curseforge]
file-id = 3344001
project-id = 436038
release-channel = "beta"
