name = "IMBlockerFabric"
filename = "imblockerfabric-1.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3254/510/imblockerfabric-1.0.12.jar"
hash-format = "murmur2"
hash = "4217437040"

[update]
[update.curseforge]
file-id = 3254510
project-id = 399225
release-channel = "beta"
