name = "Item Model Fix (Fabric)"
filename = "item-model-fix-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3294/267/item-model-fix-1.0.1.jar"
hash-format = "murmur2"
hash = "456748976"

[update]
[update.curseforge]
file-id = 3294267
project-id = 399798
release-channel = "beta"
