name = "Lithium"
filename = "lithium-fabric-mc1.17-0.7.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17-0.7.0/lithium-fabric-mc1.17-0.7.0.jar"
hash-format = "sha512"
hash = "9c0c9a98896966b4728d9ccb1b7605b3229599197f9ffaf6c12cb15deb28e0cb99be85e46772d1d258820e2385f1aa73aa7cb862ec9383e7e242baefc6eb7921"

[update]
[update.modrinth]
mod-id = "gvQqBUqZ"
version = "Le0tKjFX"
