name = "MinecraftCapes Mod"
filename = "MinecraftCapes Fabric 1.17-v10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3350/516/MinecraftCapes Fabric 1.17-v10.jar"
hash-format = "murmur2"
hash = "1884606024"

[update]
[update.curseforge]
file-id = 3350516
project-id = 359836
release-channel = "beta"
