name = "MinecraftCapes Mod"
filename = "MinecraftCapes Fabric 1.17-v10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/316/MinecraftCapes Fabric 1.17-v10.jar"
hash-format = "murmur2"
hash = "2156269020"

[update]
[update.curseforge]
file-id = 3344316
project-id = 359836
release-channel = "beta"
