name = "MinecraftCapes Mod"
filename = "MinecraftCapes Fabric 1.16.5-v10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3169/541/MinecraftCapes Fabric 1.16.5-v10.jar"
hash-format = "murmur2"
hash = "1265824753"

[update]
[update.curseforge]
file-id = 3169541
project-id = 359836
release-channel = "beta"
