name = "Mod Menu"
filename = "modmenu-2.0.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/mOgUt4GM/versions/2.0.1/modmenu-2.0.1.jar"
hash-format = "sha512"
hash = "aa24622bc99ac50783cb24a41acc674faf420f2a72bdff104ec8b633a4f61d6bb298f3730903b0cb07456e6eec0963425d7c38990e748725a425a576af7dc73d"

[update]
[update.modrinth]
mod-id = "mOgUt4GM"
version = "fEUlbFzP"
