name = "multiconnect"
filename = "multiconnect-1.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/32/multiconnect-1.4.3.jar"
hash-format = "murmur2"
hash = "3107088666"

[update]
[update.curseforge]
file-id = 3349032
project-id = 336018
release-channel = "beta"
