name = "Not Enough Animations (Forge/Fabric)"
filename = "notenoughanimations-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3258/203/notenoughanimations-1.2.3.jar"
hash-format = "murmur2"
hash = "2806785198"

[update]
[update.curseforge]
file-id = 3258203
project-id = 433760
release-channel = "beta"
