name = "Not Enough Animations (Forge/Fabric)"
filename = "notenoughanimations-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/120/notenoughanimations-1.2.0.jar"
hash-format = "murmur2"
hash = "2345887998"

[update]
[update.curseforge]
file-id = 3243120
project-id = 433760
release-channel = "beta"
