name = "Not Enough Animations (Forge/Fabric)"
filename = "notenoughanimations-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/830/notenoughanimations-1.2.1.jar"
hash-format = "murmur2"
hash = "2637222886"

[update]
[update.curseforge]
file-id = 3243830
project-id = 433760
release-channel = "beta"
