name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-6.0.250-alpha-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/113/RoughlyEnoughItems-6.0.250-alpha-fabric.jar"
hash-format = "murmur2"
hash = "3592306871"

[update]
[update.curseforge]
file-id = 3349113
project-id = 310111
release-channel = "beta"
