name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-3.0.0-alpha.4+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/697/shulkerboxtooltip-3.0.0-alpha.4+1.17.jar"
hash-format = "murmur2"
hash = "3557760708"

[update]
[update.curseforge]
file-id = 3348697
project-id = 315811
release-channel = "beta"
