name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-3.0.0-alpha.3+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/740/shulkerboxtooltip-3.0.0-alpha.3+1.17.jar"
hash-format = "murmur2"
hash = "1704059795"

[update]
[update.curseforge]
file-id = 3344740
project-id = 315811
release-channel = "beta"
