name = "'Slight' Gui Modifications"
filename = "slight-gui-modifications-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3337/706/slight-gui-modifications-2.0.0.jar"
hash-format = "murmur2"
hash = "3835503898"

[update]
[update.curseforge]
file-id = 3337706
project-id = 380393
release-channel = "beta"
