name = "ToolTipFix"
filename = "tooltipfix-1.0.2-1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/68/tooltipfix-1.0.2-1.17.jar"
hash-format = "murmur2"
hash = "2994899850"

[update]
[update.curseforge]
file-id = 3351068
project-id = 411557
release-channel = "beta"
