name = "TRansliterationLib"
filename = "TRansliterationLib-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/117/TRansliterationLib-1.0.3.jar"
hash-format = "murmur2"
hash = "2855056746"

[update]
[update.curseforge]
file-id = 3243117
project-id = 441024
release-channel = "beta"
