name = "WTHIT"
filename = "wthit-3.5.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/814/wthit-3.5.2-fabric.jar"
hash-format = "murmur2"
hash = "4154885511"

[update]
[update.curseforge]
file-id = 3348814
project-id = 440979
release-channel = "beta"
