name = "WTHIT"
filename = "wthit-fabric-3.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3356/124/wthit-fabric-3.6.0.jar"
hash-format = "murmur2"
hash = "3614275441"

[update]
[update.curseforge]
file-id = 3356124
project-id = 440979
release-channel = "beta"
