name = "WTHIT"
filename = "wthit-3.5.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3350/383/wthit-3.5.3-fabric.jar"
hash-format = "murmur2"
hash = "3828655911"

[update]
[update.curseforge]
file-id = 3350383
project-id = 440979
release-channel = "beta"
