name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.4.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3233/114/Xaeros_Minimap_21.4.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "249792166"

[update]
[update.curseforge]
file-id = 3233114
project-id = 263420
release-channel = "beta"
