name = "Xaero's World Map"
filename = "XaerosWorldMap_1.14.1_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3321/957/XaerosWorldMap_1.14.1_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "770240249"

[update]
[update.curseforge]
file-id = 3321957
project-id = 317780
release-channel = "beta"
