name = "Xaero's World Map"
filename = "XaerosWorldMap_1.12.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3233/118/XaerosWorldMap_1.12.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "1711702028"

[update]
[update.curseforge]
file-id = 3233118
project-id = 317780
release-channel = "beta"
