name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.10.0.4_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/163/Xaeros_Minimap_21.10.0.4_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "4026859102"

[update]
[update.curseforge]
file-id = 3343163
project-id = 263420
release-channel = "beta"
